# Generated by Django 2.2.9 on 2019-12-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0002_auto_20191223_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='abc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='abc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
