# Generated by Django 2.2.9 on 2019-12-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('hot_dogs', models.BooleanField(default=False)),
                ('pizza', models.BooleanField(default=False)),
                ('place_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='restaurant', serialize=False, to='multitable.Place')),
                ('near_place', models.ManyToManyField(related_name='restaurant_set', to='multitable.Place')),
            ],
            bases=('multitable.place',),
        ),
    ]
