# Generated by Django 2.2.9 on 2019-12-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookUser',
        ),
    ]
